### ISSUE TITLE
new spreadsheet

### ISSUE THREAD

**Issue by cmhiggin** [digiah/pidginmapping#4]
[Mapping language 10.24.17.xlsx](https://github.com/digiah/pidginmapping/files/1416163/Mapping.language.10.24.17.xlsx)
new spreadsheet

**Comment by damg70** [comment]
Cleaned up spreadsheet and sever... a few remaining files are not logged in the DB, e.g. Big City Diner.

EXPORT new DB TABLE as master CSV.

**Comment by damg70** [comment]
new master csv spreadsheet uploaded to repo 10-25

_mapping_language_MASTER_10-25.csv

download it to your laptop @cmhiggin
